### PR TITLE
Add `nix` support for local development

### PR DESCRIPTION
**Pull request by monadplus**
It features:
- Building both packages, generating the documentation and running packages tests in a reproducible environment through a single command: `nix build .#libsodium-bindings` and `nix build .#sel`, respectively.
- A _deterministic_ environment multi-platform to build both packages using Cabal: `nix develop`. This environment includes:
  - GHC 9.4.5
  - Cabal 3.10 with all required packages installed
  - The right version of HLS
  -  All formatters: cabal-fmt, fourmolu, and nixpkgs-fmt
  - All linters: hlint
  - Installed githooks that prevent committing without formatting (`*.cabal`, `*.hs`, and `*.nix`) and linting.
- Integration with [direnv](https://direnv.net/) through [nix-direnv](https://github.com/nix-community/nix-direnv).
- Backwards compatibility with `nix-build` and `nix-shell`.

It does not feature:
- Integration with CI.

This PR was motivated by my own needs. @TeofilC gently asked me to review the documentation, but I couldn't compile the packages and generate the latest documentation. Apart from that, I was lacking tooling such as cabal-fmt, fourmolu, etc. So, I decided to write a nix derivation `default.nix` to fulfill those needs (first commit). A week later, I started learning about flakes and decided to port this derivation to `flake.nix`.

This nix integration really helped me get the development environment I needed for this project without having to install all the dependencies and tooling. I thought it may also be beneficial for others, and so I talked with @TeofilC to see if this project was open to integrate with nix and they responded positively. I understand that giving support to nix may inquire a small additional maintenance cost, so up you folks whether to finally accept this MR or not. 

P.S. I have only been using flakes for a few day, so there's probably a lot of ways to improve this work, so suggestions are always welcome!

### CODE REVIEW

**Comment by Kleidukos** [comment]
> but I couldn't compile the packages and generate the latest documentation

Hmm you're getting me worried here, what was the problem?

**Comment by Kleidukos** [comment]
@MangoIV Nix Flakes wizard, I summon thee!

**Comment by monadplus** [comment]
> Hmm you're getting me worried here, what was the problem?

Don't worry, this projects compiles flawlessly with cabal. It was a problem on my end: I'm driving an arch with most dependencies installed through nix (weird combination I known), and my cabal was missing sodium.

**Comment by MangoIV** [comment]
Looks good on first glance, can try out later.

**Comment by monadplus** [comment]
One thing that would be great to fix is that `cabal repl` does fail (and so `ghcid`) on the nix shell. It's because it's missing the sodium dynamic lib, but I didn't know how to override it :disappointed: @TeofilC @MangoIV

**Comment by MangoIV** [comment]
I can most probably deal with that, will perhaps not do it today though, so bare with me until tomorrow :3

**Comment by Kleidukos** [comment]
Perfect, glad to see we have a solution. :)

**Comment by TeofilC** [comment]
No worries at all for tagging me, but I think you've got me confused with someone else.
I'm used to being the only Teofil around so it's refreshing to be confused with someone else 😄

FWIW I think this is the issue you are running into: https://github.com/NixOS/nixpkgs/issues/56860
I think you can work-around this by enabling the pkg-config flags in your shell and adding `pkgs.pkg-config` to your `buildInputs`

**Comment by monadplus** [comment]
Sorry for tagging you by mistake Teo.. I was trying to tag Kleidukos instead :bow:

**Comment by TeofilC** [comment]
Don't worry about it at all!

**Pull request closed without merging**
