### PR TITLE
fixup nix

### PR DESCRIPTION
**Pull request by MangoIV**
This supercedes #83 with some refactoring and simplification such as: 
- make everything compile in both packages and cabal
- refactor some of the nix
- make the package generation more reliable
- add packages and shell to checks
- reduce flake inputs
- allow for `nix flake check` with `--impure`
- reduce complexity in overlay
- added workflow to check both nix packages as well as the `devShell`
- added cachix pubkey and url in extra substitutors  

cc @monadplus

### CODE REVIEW

**Comment by MangoIV** [comment]
This relies on IFD which is necessary to make the package generation reliable in case of the upstream version adding e.g. more dependencies than the version currently on hackage (which is very probable)

**Comment by monadplus** [comment]
Thanks for fixing my mess <3

Do you think it is worth prefixing the packages by the compiler version? We could add outputs for the supported GHC versions in cabal by just parametrizing the some parts, but probably it won't be that easy to make everything compile.

**Comment by MangoIV** [comment]
@Kleidukos I think this is ready for review :)

**Comment by MangoIV** [comment]
@monadplus Would be happy about a review from you for at least the small parts you didn't write yourself, as well :3

**Comment by monadplus** [comment]
I run all outputs on a x86-64 linux successfully. It would be useful to test on a darwin arm, but not necessary.

The changes seem reasonable. You enabled incremental compilation, improved the cabal pkg-config, and fixed the missing dyn dependency on the repl.

I see you removed some of the tools likes hlint. Is there a reason for that? I know the commit-hook run those for you, but it is still worth having them while developing. Maybe hls provides hlint? Anyway, I am ok with those changes.

Awesome work!

**Comment by MangoIV** [comment]
> Is there a reason for that

There was at first, because I assumed that the only place we would need hlint is the pre-commit-hook, but you're right, we need it for hls as well, I will add it back. 

wrt the nix formatters I think it's fine to only have it in pchs, that gives it less chance for divergence

**Comment by MangoIV** [comment]
at the moment I think they can't diverge because they have the same nixpkgs

**Comment by MangoIV** [comment]
but theoretically they can that's why I removed most of them

**Comment by MangoIV** [comment]
> `LD_LIBRARY_PATH` 

this and pkgconfigdepends

**Review by Kleidukos — APPROVED** [review]
let's go!

**Pull request merged**
